# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8af62e5efe7f5f0fa2dbd3de7562b728fbc988b5b636c416d6db51a2ef7fb452bdee117785be2b88a8849e115f12c8d2c80a10eb407482f0d36a04be34636707

test:
  secret_key_base: ff50098c6300e964aa42d0c5b3edeb84a1329ff84af532899d810830152e55868a8c26422ff753da91512957e3a0034da2fdeedd052f123a4354deb2a63cce84

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
